### ISSUE TITLE
打造自己的看番环境

### ISSUE THREAD

**Issue by bznsix** [bznsix/bznsix.github.io#12]
由于当前的B站特色，很多番剧先审后播，时效性有所下降，所以考虑在本地搭建一套自己的看番环境，本次主要使用的工具有qbittorrent和jellyfin。
**Qbittorent**
这是一个P2P下载器，可以允许你从RSS源订阅下载种子，并且可以自动更新，这样就可以达到有字幕组更新后我们自动下载的效果。
首先配置下RSS相关 设置->选项
![image](https://github.com/bznsix/bznsix.github.io/assets/38829902/e91db5b4-5024-4cfc-bb96-be0bff9acf2f)
然后点击右侧RSS 点击加号 就可以添加RSS订阅链接了
![image](https://github.com/bznsix/bznsix.github.io/assets/38829902/e5ffd5e5-bf56-4bf0-9c7e-a231de95e40f)
RSS链接获取的网站可以选用 [这个](https://share.acgnx.se/)，注意将这个网站添加到你的科学规则中，不然RSS会订阅失败。
订阅成功后选择RSS下载器，添加一条规则，筛选出你想要的字幕组的规则，清晰度，然后勾选对你刚才订阅的RSS应用当前规则。
![image](https://github.com/bznsix/bznsix.github.io/assets/38829902/d4d17466-123f-4485-a0e3-3737a5d2ab0d)
这时候你就能看到你选中的正在下载
![image](https://github.com/bznsix/bznsix.github.io/assets/38829902/f31bd4c7-d8a8-4e25-b6c4-30f47b3f4bf4)
附上qbittorrent的docker-compose.yml
```
version: "3.9"

services:
  qbittorrent-nox:
    container_name: qbittorrent-nox
    environment:
      - QBT_EULA=accept
      - QBT_VERSION=latest
      - QBT_WEBUI_PORT=8080
    image: qbittorrentofficial/qbittorrent-nox:latest
    ports:
      - 6881:6881/tcp
      - 6881:6881/udp
      - 8080:8080/tcp
    read_only: true
    stop_grace_period: 30m
    tmpfs:
      - /tmp
    tty: true
    volumes:
      - ./config:/config
      - /media:/downloads
```
我们把外面的media映射到了里面的downloads所以你的动漫应该都在media里面。
**Jellyfin**
jellyfin直接使用以下命令安装，亲测插件库可以用，别用别的compose等安装，插件库死活刷不出来
```
docker run -d    --net=host    --name=jellyfin    -p 8096:8096    -v ./config:/config    -v /media:/media    --restart=unless-stopped    jellyfin/jellyfin
```
我们这里需要挂在/media到内部的/media以此实现下载的资源直接刮削的效果
点击控制台->插件->存储库 添加如下存储库：https://jellyfin-plugin-bangumi.pages.dev/repository.json
![image](https://github.com/bznsix/bznsix.github.io/assets/38829902/71def993-542c-481d-9e45-606cc8b74ab9)
之后点击目录安装我们的bangumi，这样就完成了刮削的配置
试看一下刮削的效果：
![image](https://github.com/bznsix/bznsix.github.io/assets/38829902/a913bf95-b69c-4db8-812d-5ab1e6d5afc6)
效果挺不错
